/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog.grupo9tp5;

import java.util.ArrayList;

/**
 *
 * @author gonza
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    /**
     * Creates new form frmMenuPrincipal
     */
    static Directorio directorio;
    static ArrayList<String> ciudades;

    public frmMenuPrincipal() {
        initComponents();
        directorio = new Directorio();
        ciudades = new ArrayList<>();
        ciudades.add("San Luis");
        ciudades.add("Merlo");
        ciudades.add("Villa Mercedes");
        cargarContactosDePrueba();
    
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuAgregarCliente = new javax.swing.JMenuItem();
        mnuBuscarCliente = new javax.swing.JMenuItem();
        mnuBorrarCliente = new javax.swing.JMenuItem();
        mnuDirectorio = new javax.swing.JMenu();
        mnuBuscarPorCiudad = new javax.swing.JMenuItem();
        mnuBuscarPorApellido = new javax.swing.JMenuItem();
        mnuCiudades = new javax.swing.JMenu();
        mnuAgregarCiudad = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(1080, 650));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1471, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        mnuClientes.setText("Clientes");

        mnuAgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAgregarCliente.setText("Agregar Cliente");
        mnuAgregarCliente.addActionListener(this::mnuAgregarClienteActionPerformed);
        mnuClientes.add(mnuAgregarCliente);

        mnuBuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarCliente.setText("Buscar Cliente");
        mnuBuscarCliente.addActionListener(this::mnuBuscarClienteActionPerformed);
        mnuClientes.add(mnuBuscarCliente);

        mnuBorrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBorrarCliente.setText("Borrar Cliente");
        mnuBorrarCliente.addActionListener(this::mnuBorrarClienteActionPerformed);
        mnuClientes.add(mnuBorrarCliente);

        jMenuBar1.add(mnuClientes);

        mnuDirectorio.setText("Directorio");

        mnuBuscarPorCiudad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarPorCiudad.setText("Buscar Cliente Por Ciudad");
        mnuBuscarPorCiudad.addActionListener(this::mnuBuscarPorCiudadActionPerformed);
        mnuDirectorio.add(mnuBuscarPorCiudad);

        mnuBuscarPorApellido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarPorApellido.setText("Buscar Teléfono por Apellido");
        mnuBuscarPorApellido.addActionListener(this::mnuBuscarPorApellidoActionPerformed);
        mnuDirectorio.add(mnuBuscarPorApellido);

        jMenuBar1.add(mnuDirectorio);

        mnuCiudades.setText("Ciudades");

        mnuAgregarCiudad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAgregarCiudad.setText("Agregar Ciudad");
        mnuAgregarCiudad.addActionListener(this::mnuAgregarCiudadActionPerformed);
        mnuCiudades.add(mnuAgregarCiudad);

        jMenuBar1.add(mnuCiudades);

        mnuOpciones.setText("Opciones");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(this::mnuSalirActionPerformed);
        mnuOpciones.add(mnuSalir);

        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void centrarEnEscritorio(javax.swing.JInternalFrame frame) {
        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    private void mnuAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarCiudadActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregarCiudad fbc = new frmAgregarCiudad();
        centrarEnEscritorio(fbc);
        fbc.setVisible(true);
        escritorio.add(fbc);
        escritorio.moveToFront(fbc);
    }//GEN-LAST:event_mnuAgregarCiudadActionPerformed

    private void mnuBuscarPorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarPorApellidoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscarTelPorApellido fbpa = new frmBuscarTelPorApellido();
        fbpa.setVisible(true);
        escritorio.add(fbpa);
        escritorio.moveToFront(fbpa);
    }//GEN-LAST:event_mnuBuscarPorApellidoActionPerformed

    private void mnuBuscarPorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarPorCiudadActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscarPorCiudad fbpc = new frmBuscarPorCiudad();
        fbpc.setVisible(true);
        escritorio.add(fbpc);
        escritorio.moveToFront(fbpc);
    }//GEN-LAST:event_mnuBuscarPorCiudadActionPerformed

    private void mnuBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBorrarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBorrarCliente fdelc = new frmBorrarCliente();
        fdelc.setVisible(true);
        escritorio.add(fdelc);
        escritorio.moveToFront(fdelc);
    }//GEN-LAST:event_mnuBorrarClienteActionPerformed

    private void mnuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscarCliente fbc = new frmBuscarCliente();
        fbc.setVisible(true);
        escritorio.add(fbc);
        escritorio.moveToFront(fbc);
    }//GEN-LAST:event_mnuBuscarClienteActionPerformed

    private void mnuAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregar fa = new frmAgregar();
        fa.setVisible(true);
        escritorio.add(fa);
        escritorio.moveToFront(fa);
    }//GEN-LAST:event_mnuAgregarClienteActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed
    private void cargarContactosDePrueba() {
        directorio.agregarContacto(2645551111L, 30111222, "Ana", "Gomez", "San Luis", "Calle 1");
        directorio.agregarContacto(2645552222L, 30222333, "Luis", "Perez", "Merlo", "Calle 2");
        directorio.agregarContacto(2645553333L, 30333444, "Juan", "Saez", "San Luis", "Calle 3");
        directorio.agregarContacto(2645554444L, 30444555, "Sofia", "Gomez", "Villa Mercedes", "Calle 4");
        directorio.agregarContacto(2645555555L, 30555666, "Marta", "Diaz", "San Luis", "Calle 5");
        directorio.agregarContacto(2645556666L, 30333444, "Juan", "Saez", "Merlo", "Calle 6"); // mismo DNI que Juan, otro teléfono
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAgregarCiudad;
    private javax.swing.JMenuItem mnuAgregarCliente;
    private javax.swing.JMenuItem mnuBorrarCliente;
    private javax.swing.JMenuItem mnuBuscarCliente;
    private javax.swing.JMenuItem mnuBuscarPorApellido;
    private javax.swing.JMenuItem mnuBuscarPorCiudad;
    private javax.swing.JMenu mnuCiudades;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuDirectorio;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
